### ISSUE TITLE
Stylelint v14 support

### ISSUE THREAD

**Issue by jens-duttke** [Donov4n/stylelint-find-new-rules#12]
It would be great if this code could be updated to support Stylelint v14, because right now npm returns this error on installation:

> npm ERR! Found: stylelint@14.0.1
> npm ERR! node_modules/stylelint
> npm ERR!   stylelint@"14.0.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer stylelint@"^13" from stylelint-find-new-rules@3.0.2
> npm ERR! node_modules/stylelint-find-new-rules
> npm ERR!   dev stylelint-find-new-rules@"3.0.2" from the root project

**Comment by Donov4n** [comment]
Stylelint 14 has been added to the supported versions (cf. [3.0.3](https://github.com/Donov4n/stylelint-find-new-rules/blob/master/CHANGELOG.md#303-2021-11-07))
