### ISSUE TITLE
Ignore `deprecated` rules

### ISSUE THREAD

**Issue by jens-duttke** [Donov4n/stylelint-find-new-rules#15]
I'm using the `stylelint-find-new-rules` script to find all rules which are currently not configured.
In Stylelint v15, all stylistic rules are marked as deprecated, so I've removed them from my configuration.

Now `stylelint-find-new-rules` lists all of them as `[UNUSED] Available rules that are not configured`.
Is it possible through the command line tool to show all unused rules, which are NOT marked as deprecated? Because it does not make sense to add deprecated rules.

`--no-d` has no effect.

**Comment by Donov4n** [comment]
Hello :)

Can you give the Stylelint configuration you use and the list of the rules that are marked as "UNUSED" while being deprecated ?

**Comment by jens-duttke** [comment]
Hello,

your asking indicated that deprecated rules were already excluded, so I double-checked my code and found that the error was mine.

Sorry, for bothering you. btw. that's a very useful tool :-)
