### ISSUE TITLE
"Error: The "id" argument must be of type string. Received [Object: null prototype] [Module]" on `plugin objects`

### ISSUE THREAD

**Issue by jens-duttke** [Donov4n/stylelint-find-new-rules#17]
`stylelint` allows to use

> [...] either [plugin objects](https://stylelint.io/developer-guide/plugins) or "locaters" identifying the plugins [...]

See https://stylelint.io/user-guide/configure/#plugins

If I'm using plugin objects (either directly or by importing them using require/dynamic imports), `stylelint-find-new-rules` stops with the error:

> Error: The "id" argument must be of type string. Received [Object: null prototype] [Module]

The problem is here:

https://github.com/Donov4n/stylelint-find-new-rules/blob/5c2e6813775da19689a5656d45e71c4ce0712e54/lib/utils/rules.js#L14C24-L14C24

were you don't check if the plugin is a "locater" or a plugin object.

**Comment by Donov4n** [comment]
Fixed in [`4.1.2`](https://github.com/Donov4n/stylelint-find-new-rules/releases/tag/4.1.2), thanks for the report.
