### ISSUE TITLE
Doesn't work with `extends: [stylelint-prettier/recommended]`

### ISSUE THREAD

**Issue by ThiefMaster** [Donov4n/stylelint-find-new-rules#7]
```
[adrian@blackhole:~/dev/indico/src:style-lint *$]> npx stylelint-find-new-rules
npx: installed 68 in 2.488s
Error: Cannot use import statement outside a module
```

This happens during `_gatherPluginsRules(extendedConfig)`; if I skip it for the `stylelint-prettier/recommended` extends entry everything works fine; same if I remove this particular extend from my config.

**Comment by Donov4n** [comment]
Thanks for the report.

The problem should be fixed in version 2.0.0 which has just been released.
